version: '3'

services:
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./kafka:/var/lib/kafka/data

  spark:
    image: bitnami/spark
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=master

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra:/var/lib/cassandra/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

